/* NOTE: Do not edit this file, this file is auto generated */

import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './page.tsx'

if (typeof document !== 'undefined') {

  ReactDOM.hydrateRoot(
    document,
    <React.StrictMode>
      <App />
    </React.StrictMode>
  )
}