/* NOTE: Do not edit this file, this file is auto generated */

import React from 'react'
import ReactDOM from 'react-dom/client'
import { RouterProvider, createBrowserRouter } from 'react-router-dom'
import routes from '.mrh/routes'

if (typeof document !== 'undefined') {
  const router = createBrowserRouter(routes)

  ReactDOM.hydrateRoot(
    document,
    <React.StrictMode>
      <RouterProvider router={router} />
    </React.StrictMode>
  )
}
