import { existsSync, readdirSync, statSync, writeFileSync } from 'node:fs'

const string = `/* NOTE: Do not edit this file, this file is auto generated */

import React from 'react'
import ReactDOM from 'react-dom/client'
import { RouterProvider, createBrowserRouter } from 'react-router-dom'
import routes from '.mrh/routes'

if (typeof document !== 'undefined') {
  const router = createBrowserRouter(routes)

  ReactDOM.hydrateRoot(
    document,
    <React.StrictMode>
      <RouterProvider router={router} />
    </React.StrictMode>
  )
}`

const dirs = readdirSync('src/views', { recursive: true })

dirs.forEach((dir) => {
  const stats = statSync(`src/views/${dir}`)
  if (stats.isDirectory()) {
    const entryDestination = `src/views/${dir}/entry.tsx`
    if (!existsSync(entryDestination)) {
      writeFileSync(entryDestination, string, {
        encoding: 'utf-8',
      })
    }
  }
})
